disjukr/just-news

- jews.user.js
Fix #108.
Let me know if you want to revert some changes.
> Leave reporters in plain article (Fix #108)

- jews.user.js
> 이데일리 기사 내 사진 추가

- jews.user.js
관련 이슈: #126
forEach도 바꿔봤는데 별로이면 빼고 머지해주세요(?)
> $.each와 $.forEach 변경

- .editorconfig
> editorconfig 파일 추가

- src/impl/뉴데일리경제.js
See https://github.com/disjukr/jews/pull/163#issuecomment-119451454.
> Remove jQuery from 뉴데일리경제

- README.md
- src/impl/뉴스1.js
- src/impl/스포츠경향.js
- src/impl/스포츠동아.js
- src/sites.js
See https://github.com/disjukr/jews/pull/162#issuecomment-124936505.
- 54c76cf2dc50350d35d1f7077926e8a7f62808f9
- a2f5158593f6c32723086520b7e04a0842602ca8
- 821149e6898f87ed1a9baabbb58839c29965961a
- 787fd998910551a71f53e52c455765e61e08ea09
> Reflect changes of 'master' branch

- jews.user.js
Iframe 등의 동영상의 최대 사이즈를 640px x 480px로 제한함.
> Set Maximum size of all iframes

- src/impl/조선일보.js
> [Modern] 조선일보 재구성

- src/impl/YTN.js
> modern branch YTN 수정

- src/impl/뉴데일리.js
- src/reconstruct.js
> modern branch 뉴데일리 수정

- src/impl/뉴데일리경제.js
> 뉴데일리 경제 수리

- src/impl/한국경제.js
- src/test/suite/basic.js
> 한국경제 제목, 작성일, 수정일 안 보이는 문제 수정

- src/impl/헤럴드경제.js
> Remove ads from 헤럴드경제

- src/impl/한국일보.js
- src/test/suite/basic.js
> Fix parsing 한국일보

- src/impl/YTN.js
> YTN 내용 잘리는 문제 수정

- src/impl/경향신문.js
> 경향신문 광고 제거

- src/sites.js
> 아시아경제 주소 추가

- src/impl/서울신문.js
> 서울신문 제목, 작성일 나오게 수정

- src/impl/민중의소리.js
> Fix unexpected token error

- README.md
- src/impl/네이버뉴스.js
- src/sites.js
Tested with:
- http://news.naver.com/main/hotissue/read.nhn?mid=hot&sid1=102&cid=984650&iid=25956277&oid=001&aid=0009196980&ptype=052
- http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=103&oid=437&aid=0000152406
> Support 네이버뉴스

- src/impl/동아일보.js
> Fix timestamps and remove ads for 동아일보

- src/impl/연합뉴스.js
> 연합뉴스 광고 제거

- src/impl/전자신문.js
> Update for 전자신문

- src/impl/YTN.js
> YTN 한컷뉴스 내용 누락 수정

- README.md
`-c-1` 없이 띄웠을 때 캐싱 옵션 때문인지 Tampermonkey에서 스크립트 새로고침이 제대로 되지 않는 것 같더라고요.
> Specify `-c-1` option to disable caching

- src/impl/프레시안.ts
Fix #296.
Link: <http://www.pressian.com/news/article.html?no=198886#09T0>
> Fix parsing bugs for pressian.com

- README.md
- src/impl/디지털데일리.ts
- src/sites.ts
> Support ddaily.co.kr

- src/impl/MBC.ts
this patch have these changes:
- support last modified time
- support movie player
this patchset was only tested in firefox
resolve #303
> MBC: Fix parsing problem.

- README.md
- src/impl/다음뉴스.ts
- src/sites.ts
https://mobile.twitter.com/plafina/status/1120161164795629568
52시간 근무 기획기사 읽는데 just-news 덕분에 편하게 잘 읽었습니다. 좋은 프로젝트 감사드립니다.
기사 중 다음뉴스만 아직 적용이 안되어있어 추가해보았습니다.
> 사이트 추가: 다음뉴스

- .vscode/just-news.code-snippets
> VSCode Snippet 추가

- src/impl/매일경제.ts
> 매일경제 내용 버그 수정

- src/impl/지디넷코리아.ts
- src/sites.ts
> 지디넷에서 동작하도록 수정

- src/impl/머니투데이.ts
> 머니투데이 날짜 제대로 표시되지 않는 문제 해결.

- src/impl/허핑턴포스트.ts
- src/test/health-check/index.ts
허핑턴 포스트 깨져있길래 고쳐봤습니다. 
close #358
> 허핑턴 포스트 깨져있던 것 수정합니다.

- src/impl/경향신문-모바일.ts
파싱 범위 선택자인 `readyToParse` 정보를 모바일에 맞게 수정하였습니다.
> 경향신문 모바일 선택자 업데이트

- src/impl/허핑턴포스트.ts
- src/view/Settings.tsx
close #361 
설정창 바깥을 클릭하면 설정창이 닫히도록 만듭니다. 하는김에 허핑턴 포스트 로딩 속도도 조금 개선했습니다.
> 설정창 바깥을 클릭하면 닫히도록

- .github/workflows/schedule.yml
- https://github.com/disjukr/just-news/issues/352 이슈를 해결합니다.
- 매일 0시 0분에 단위 테스트를 실행합니다.
- 이 스크립트는 `schedule.yml`에 작성했습니다.
> 뉴스사이트 변경을 감지하기 위해 매일 0시 0분에 테스트를 실행합니다

- .github/workflows/push.yml
> Fix Github Action failed

- src/test/health-check/index.ts
나우뉴스랑 네이버뉴스 url 추가해보았습니다!
이러한 방식으로 추가하는 것이 맞다면 나머지도 추가해서 올리겠습니다!
그리고 노켓뉴스를 추가하려고 해봤는데 이미 적용이 돼서 나오는데 어떻게 된건지 궁금합니다!
> 나우뉴스, 네이버뉴스 테스트 추가

- src/test/health-check/index.ts
health-check 테스트 케이스 전체 추가하였습니다!
한번 더 검토하고 pull request하고 싶었는데 방법을 몰라 일단 올렸습니다.!
제가 수정 제출이 바로 가능하면 재컴토 해보고 답글 남기겠습니다. 불가능하다면 저번처럼 권한 주시기 바랍니다!
또한, 지원현황도 정리해보려고 하는데 순서를 여기에 맞춰해도 될지 여쭤봅니다!
> health-check 테스트 케이스 TODO 항목 전부 작성

- src/test/health-check/index.ts
> health-check 파일 검수
